
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX sf: <http://www.opengis.net/ont/sf#>

PREFIX ont: <http://openis.ititou.be/ont#>
PREFIX exont: <http://webprotege.stanford.edu/ontologies/ExerciseOntology#>

SELECT DISTINCT ?ex ?track ?geom
WHERE {
    ?ex rdf:type exont:Exercise.
    ?ex exont:HasType "Biking".
    ?ex ont:hasTrack ?track.
    ?track geo:hasGeometry ?geom.
}