# Query all tracks within a bounding box

PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sf: <http://www.opengis.net/ont/sf#>
PREFIX ont: <http://openis.ititou.be/ont#>

SELECT DISTINCT ?geom
WHERE {
    ?track rdf:type ont:Track.
    ?track geo:hasGeometry ?geom.

    FILTER (
        geof:sfContains(
            STRDT("POLYGON((3 50, 3 51, 5 51, 5 50, 3 50))", sf:wktLiteral),        
            STRDT(?geom, sf:wktLiteral)
        )
    ).
}
