# Find all tracks crossing track #1

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX sf: <http://www.opengis.net/ont/sf#>

PREFIX ont: <http://openis.ititou.be/ont#>

SELECT DISTINCT ?track ?geom
WHERE {
    ?track rdf:type ont:Track.
    ?track geo:hasGeometry ?geom.
    <http://localhost/track/1> geo:hasGeometry ?x.

    FILTER (
        geof:sfIntersects(STRDT(?x, sf:wktLiteral), STRDT(?geom, sf:wktLiteral))
    ).
}
