# Query all tracks within a bounding box

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX sf: <http://www.opengis.net/ont/sf#>

PREFIX tr: <http://openis.ititou.be/ont#>

SELECT DISTINCT ?track ?geom
WHERE {
    ?track rdf:type tr:Track.
    ?track geo:hasGeometry ?geom.

    FILTER (
        geof:sfContains(
            STRDT("POLYGON((4.15 50, 4.15 51, 4.4 51, 4.4 50, 4.15 50))", sf:wktLiteral),        
            STRDT(?geom, sf:wktLiteral)
        )
    ).
}
